/* ==========================================================================
   DailyTools Hub — Tool Registry
   Single source of truth for every tool: used by search, homepage sections,
   category pages, and "related tools" blocks. Add a new tool by adding one
   object here — no other file needs to change for it to be searchable.
   ========================================================================== */

const TOOLS = [
  {
    id: "age-calculator",
    name: "Age Calculator",
    desc: "Calculate your exact age in years, months and days.",
    url: "tools/age-calculator.html",
    category: "Date & Time",
    keywords: ["age", "birthday", "born", "years old", "dob"],
    icon: "cake",
    emoji: "🎂",
    popular: true,
    quick: true,
  },
  {
    id: "emi-calculator",
    name: "EMI Calculator",
    desc: "Calculate your monthly loan payment quickly.",
    url: "tools/emi-calculator.html",
    category: "Money & Finance",
    keywords: ["emi", "loan", "installment", "interest", "mortgage"],
    icon: "landmark",
    emoji: "🏦",
    popular: true,
    quick: true,
  },
  {
    id: "percentage-calculator",
    name: "Percentage Calculator",
    desc: "Find percentages, increases and decreases instantly.",
    url: "tools/percentage-calculator.html",
    category: "Money & Finance",
    keywords: ["percentage", "percent", "%", "of"],
    icon: "percent",
    emoji: "📊",
    popular: true,
    quick: true,
  },
  {
    id: "gst-calculator",
    name: "GST Calculator",
    desc: "Add or remove GST from any amount in seconds.",
    url: "tools/gst-calculator.html",
    category: "Money & Finance",
    keywords: ["gst", "tax", "vat", "goods and services tax"],
    icon: "receipt",
    emoji: "🧾",
    popular: true,
    quick: true,
  },
  {
    id: "discount-calculator",
    name: "Discount Calculator",
    desc: "Work out sale prices and how much you save.",
    url: "tools/discount-calculator.html",
    category: "Money & Finance",
    keywords: ["discount", "sale", "off", "coupon", "savings"],
    icon: "tag",
    emoji: "🏷️",
    popular: false,
    quick: false,
  },
  {
    id: "salary-calculator",
    name: "Salary Calculator",
    desc: "Convert monthly to annual salary with estimated deductions.",
    url: "tools/salary-calculator.html",
    category: "Money & Finance",
    keywords: ["salary", "ctc", "take home", "in hand", "income"],
    icon: "wallet",
    emoji: "💰",
    popular: false,
    quick: false,
  },
  {
    id: "date-calculator",
    name: "Date Calculator",
    desc: "Find the difference between dates, or add/subtract days.",
    url: "tools/date-calculator.html",
    category: "Date & Time",
    keywords: ["date", "difference", "add days", "subtract days"],
    icon: "calendar",
    emoji: "📅",
    popular: false,
    quick: false,
  },
  {
    id: "days-calculator",
    name: "Days Calculator",
    desc: "Count days between two dates, or days until/since a date.",
    url: "tools/days-calculator.html",
    category: "Date & Time",
    keywords: ["days", "countdown", "days left", "days since"],
    icon: "calendar-days",
    emoji: "🗓️",
    popular: false,
    quick: false,
  },
  {
    id: "unit-converter",
    name: "Unit Converter",
    desc: "Convert length, weight, area, speed and volume units.",
    url: "tools/unit-converter.html",
    category: "Converters",
    keywords: ["unit", "convert", "km", "miles", "kg", "pounds", "meters", "feet"],
    icon: "ruler",
    emoji: "📏",
    popular: true,
    quick: false,
  },
  {
    id: "temperature-converter",
    name: "Temperature Converter",
    desc: "Convert between Celsius, Fahrenheit and Kelvin.",
    url: "tools/temperature-converter.html",
    category: "Converters",
    keywords: ["temperature", "celsius", "fahrenheit", "kelvin"],
    icon: "thermometer",
    emoji: "🌡️",
    popular: false,
    quick: false,
  },
  {
    id: "word-counter",
    name: "Word Counter",
    desc: "Count words, characters, sentences and reading time.",
    url: "tools/word-counter.html",
    category: "Text Tools",
    keywords: ["word count", "words", "reading time", "sentences", "paragraphs"],
    icon: "text",
    emoji: "📝",
    popular: true,
    quick: false,
  },
  {
    id: "character-counter",
    name: "Character Counter",
    desc: "Count characters, words and lines in your text.",
    url: "tools/character-counter.html",
    category: "Text Tools",
    keywords: ["character count", "letters", "text length"],
    icon: "case-sensitive",
    emoji: "🔤",
    popular: false,
    quick: false,
  },
  {
    id: "qr-generator",
    name: "QR Code Generator",
    desc: "Turn text, links or contact info into a QR code.",
    url: "tools/qr-generator.html",
    category: "General Utilities",
    keywords: ["qr", "qr code", "barcode", "scan"],
    icon: "qr-code",
    emoji: "🔳",
    popular: true,
    quick: true,
  },
  {
    id: "password-generator",
    name: "Password Generator",
    desc: "Create strong, random passwords instantly.",
    url: "tools/password-generator.html",
    category: "Security",
    keywords: ["password", "generator", "random", "secure"],
    icon: "key-round",
    emoji: "🔐",
    popular: true,
    quick: false,
  },
  {
    id: "image-compressor",
    name: "Image Compressor",
    desc: "Shrink JPG, PNG and WebP images without losing quality.",
    url: "tools/image-compressor.html",
    category: "File Tools",
    keywords: ["image", "compress", "photo", "resize", "shrink", "reduce size"],
    icon: "image-down",
    emoji: "🖼️",
    popular: true,
    quick: true,
  },
];

const CATEGORIES = [
  { name: "Money & Finance", icon: "landmark", emoji: "💰", desc: "EMI, GST, salary and discount tools." },
  { name: "Date & Time", icon: "calendar", emoji: "📅", desc: "Age, dates and day counting." },
  { name: "File Tools", icon: "file", emoji: "📁", desc: "Compress and manage files & images." },
  { name: "Text Tools", icon: "text", emoji: "📝", desc: "Word and character counting." },
  { name: "Converters", icon: "repeat", emoji: "🔄", desc: "Units and temperature conversion." },
  { name: "Security", icon: "shield", emoji: "🔐", desc: "Passwords and safety utilities." },
  { name: "Developer Tools", icon: "code", emoji: "💻", desc: "Utilities for building software." },
  { name: "General Utilities", icon: "layout-grid", emoji: "🧰", desc: "QR codes and everyday helpers." },
];

// Helper: resolve a tool's URL relative to the current page depth
function toolUrl(tool) {
  const inToolsDir = window.location.pathname.includes("/tools/");
  if (tool.url.startsWith("tools/")) {
    return inToolsDir ? tool.url.replace("tools/", "") : tool.url;
  }
  return inToolsDir ? "../" + tool.url : tool.url;
}
